parameters:
    strichliste:
        paypal:
            enabled: false
            recipient: "foo@bar.com"
            fee: 0

        user:
            # See http://de.php.net/manual/en/datetime.formats.relative.php
            stalePeriod: '10 day'

        i18n:
            dateFormat: 'YYYY-MM-DD HH:mm:ss'
            timezone: 'auto'
            language: 'en'
            currency:
                name: 'Euro'
                symbol: 'â‚¬'
                alpha3: 'EUR'

        account:
            boundary:
                upper: 20000
                lower: -20000

        # Be aware: All amounts are in cents!
        payment:
            undo:
                enabled: true
                delete: false
                timeout: '5 minute' # See http://de.php.net/manual/en/datetime.formats.relative.php

            boundary:
                upper: 200000
                lower: -200000

            transactions:
                enabled: true

            deposit:
                enabled: true
                custom: true
                steps:
                    - 50
                    - 100
                    - 200
                    - 500
                    - 1000
                    - 1500
                    - 2000

            dispense:
                enabled: true
                custom: true
                steps:
                    - 50
                    - 100
                    - 200
                    - 500
                    - 1000
                    - 1500

